AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3bucketwithgitsync.com
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e872aee57663ae2d
      InstanceType: t2.micro
      KeyName: awscli
